services:
    tetranz_select2entity.select2entity_type:
        class: Tetranz\Select2EntityBundle\Form\Type\Select2EntityType
        arguments: ['@doctrine', '@router', '%tetranz_select2_entity.config%']
        tags:
            - { name: form.type, alias: tetranz_select2entity }

    tetranz_select2entity.autocomplete_service:
        class: Tetranz\Select2EntityBundle\Service\AutocompleteService
        arguments: ['@form.factory', '@doctrine']
